# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 950, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tabReco = QtWidgets.QWidget()
        self.tabReco.setObjectName("tabReco")
        self.grpRecoCard = QtWidgets.QGroupBox(self.tabReco)
        self.grpRecoCard.setGeometry(QtCore.QRect(20, 20, 900, 260))
        self.grpRecoCard.setObjectName("grpRecoCard")
        self.btnPurchase = QtWidgets.QPushButton(self.grpRecoCard)
        self.btnPurchase.setGeometry(QtCore.QRect(20, 40, 150, 30))
        self.btnPurchase.setObjectName("btnPurchase")
        self.txtPurchase = QtWidgets.QLineEdit(self.grpRecoCard)
        self.txtPurchase.setGeometry(QtCore.QRect(190, 40, 680, 30))
        self.txtPurchase.setObjectName("txtPurchase")
        self.btnGSTR2A = QtWidgets.QPushButton(self.grpRecoCard)
        self.btnGSTR2A.setGeometry(QtCore.QRect(20, 90, 150, 30))
        self.btnGSTR2A.setObjectName("btnGSTR2A")
        self.txtGSTR2A = QtWidgets.QLineEdit(self.grpRecoCard)
        self.txtGSTR2A.setGeometry(QtCore.QRect(190, 90, 680, 30))
        self.txtGSTR2A.setObjectName("txtGSTR2A")
        self.btnRun = QtWidgets.QPushButton(self.grpRecoCard)
        self.btnRun.setGeometry(QtCore.QRect(20, 140, 150, 35))
        self.btnRun.setObjectName("btnRun")
        self.progressBar = QtWidgets.QProgressBar(self.grpRecoCard)
        self.progressBar.setGeometry(QtCore.QRect(190, 145, 680, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.lblStatus = QtWidgets.QLabel(self.grpRecoCard)
        self.lblStatus.setGeometry(QtCore.QRect(20, 190, 850, 25))
        self.lblStatus.setObjectName("lblStatus")
        self.btnOpenFolder = QtWidgets.QPushButton(self.grpRecoCard)
        self.btnOpenFolder.setGeometry(QtCore.QRect(20, 225, 150, 30))
        self.btnOpenFolder.setObjectName("btnOpenFolder")
        self.lblLoading = QtWidgets.QLabel(self.grpRecoCard)
        self.lblLoading.setGeometry(QtCore.QRect(780, 140, 80, 80))
        self.lblLoading.setText("")
        self.lblLoading.setObjectName("lblLoading")
        self.lblLogo = QtWidgets.QLabel(self.tabReco)
        self.lblLogo.setGeometry(QtCore.QRect(20, 300, 200, 200))
        self.lblLogo.setObjectName("lblLogo")
        self.tabWidget.addTab(self.tabReco, "")
        self.tabSummary = QtWidgets.QWidget()
        self.tabSummary.setObjectName("tabSummary")
        self.lblFilter = QtWidgets.QLabel(self.tabSummary)
        self.lblFilter.setGeometry(QtCore.QRect(20, 10, 200, 20))
        self.lblFilter.setObjectName("lblFilter")
        self.cmbRiskFilter = QtWidgets.QComboBox(self.tabSummary)
        self.cmbRiskFilter.setGeometry(QtCore.QRect(20, 30, 150, 30))
        self.cmbRiskFilter.setObjectName("cmbRiskFilter")
        self.cmbRiskFilter.addItem("")
        self.cmbRiskFilter.addItem("")
        self.cmbRiskFilter.addItem("")
        self.cmbRiskFilter.addItem("")
        self.tblSummary = QtWidgets.QTableWidget(self.tabSummary)
        self.tblSummary.setGeometry(QtCore.QRect(20, 70, 900, 460))
        self.tblSummary.setObjectName("tblSummary")
        self.tblSummary.setColumnCount(0)
        self.tblSummary.setRowCount(0)
        self.btnExportSummary = QtWidgets.QPushButton(self.tabSummary)
        self.btnExportSummary.setGeometry(QtCore.QRect(770, 540, 150, 35))
        self.btnExportSummary.setObjectName("btnExportSummary")
        self.tabWidget.addTab(self.tabSummary, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GST Reconciliation Tool"))
        self.grpRecoCard.setTitle(_translate("MainWindow", "Reconciliation Panel"))
        self.btnPurchase.setText(_translate("MainWindow", "Browse Purchase"))
        self.btnGSTR2A.setText(_translate("MainWindow", "Browse GSTR2A"))
        self.btnRun.setText(_translate("MainWindow", "Run Reconciliation"))
        self.lblStatus.setText(_translate("MainWindow", "Status: Waiting..."))
        self.btnOpenFolder.setText(_translate("MainWindow", "Open Output Folder"))
        self.lblLogo.setText(_translate("MainWindow", "Logo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReco), _translate("MainWindow", "Reconciliation"))
        self.lblFilter.setText(_translate("MainWindow", "Select Risk Filter"))
        self.cmbRiskFilter.setItemText(0, _translate("MainWindow", "All"))
        self.cmbRiskFilter.setItemText(1, _translate("MainWindow", "High"))
        self.cmbRiskFilter.setItemText(2, _translate("MainWindow", "Medium"))
        self.cmbRiskFilter.setItemText(3, _translate("MainWindow", "Low"))
        self.btnExportSummary.setText(_translate("MainWindow", "Export Summary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSummary), _translate("MainWindow", "Vendor Summary"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
